[2024-01-25T22:49:37.964+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cvd_automation_pipeline.enrich_nuclei_data_task manual__2024-01-25T22:49:21.150908+00:00 [queued]>
[2024-01-25T22:49:37.971+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cvd_automation_pipeline.enrich_nuclei_data_task manual__2024-01-25T22:49:21.150908+00:00 [queued]>
[2024-01-25T22:49:37.972+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-25T22:49:37.985+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): enrich_nuclei_data_task> on 2024-01-25 22:49:21.150908+00:00
[2024-01-25T22:49:37.989+0000] {standard_task_runner.py:60} INFO - Started process 6352 to run task
[2024-01-25T22:49:37.991+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cvd_automation_pipeline', 'enrich_nuclei_data_task', 'manual__2024-01-25T22:49:21.150908+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/test_pipeline_dag.py', '--cfg-path', '/tmp/tmpa712skei']
[2024-01-25T22:49:37.992+0000] {standard_task_runner.py:88} INFO - Job 49: Subtask enrich_nuclei_data_task
[2024-01-25T22:49:38.026+0000] {task_command.py:423} INFO - Running <TaskInstance: cvd_automation_pipeline.enrich_nuclei_data_task manual__2024-01-25T22:49:21.150908+00:00 [running]> on host d1dec68e083c
[2024-01-25T22:49:38.084+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cvd_automation_pipeline' AIRFLOW_CTX_TASK_ID='enrich_nuclei_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-25T22:49:21.150908+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-25T22:49:21.150908+00:00'
[2024-01-25T22:49:38.087+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_pipeline_dag.py", line 145, in enrich_nuclei_data
    nuclei_data = json.load(file)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 60784)
[2024-01-25T22:49:38.095+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cvd_automation_pipeline, task_id=enrich_nuclei_data_task, execution_date=20240125T224921, start_date=20240125T224937, end_date=20240125T224938
[2024-01-25T22:49:38.105+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 49 for task enrich_nuclei_data_task (Extra data: line 2 column 1 (char 60784); 6352)
[2024-01-25T22:49:38.123+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-25T22:49:38.137+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
